title: working_title
author: Deniz
name: Deniz

description:
  Hi. Some stuff about me and my projects.

excerpt_separator: <!--more-->

markdown: kramdown
highlighter: rouge
exclue:
  - Gemfile
  - Gemfile.lock

permalink:           /:categories/:year/:month/:day/:title.html
paginate: 5
paginate_path:       "blog/page:num"

baseurl: ""
url: ""

social-network-links:
  github: IronicUsername
  twitter: sos
  email: "deniztoma512@gmail.com"
  linkedin: maxmuster
  instagram: max.muster
  spotify: max.muster

sass:
  style: compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

encoding: utf-8
show_drafts: TRUE
